export const routes = {
  home: '/',
  services: '/services',
  serviceDetail: (slug: string) => `/services/${slug}`,
  categories: '/services/categories',
  categoryDetail: (slug: string) => `/services/categories/${slug}`,
  materials: '/services/materials',
  materialDetail: (slug: string) => `/services/materials/${slug}`,
  industries: '/services/industries',
  industryDetail: (slug: string) => `/services/industries/${slug}`,
  standards: '/services/standards',
  labs: '/labs',
  labDetail: (slug: string) => `/labs/${slug}`,
  equipment: '/equipment',
  equipmentDetail: (slug: string) => `/equipment/${slug}`,
  rfq: '/rfq',
  rfqNew: '/rfq/new',
  rfqDetail: (id: string) => `/rfq/${id}`,
  reports: '/reports',
  reportDetail: (id: string) => `/reports/${id}`,
  about: '/about',
  contact: '/contact',
  help: '/help',
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    forgotPassword: '/auth/forgot-password',
  },
  dashboard: {
    home: '/dashboard',
    orders: '/dashboard/orders',
    orderDetail: (id: string) => `/dashboard/orders/${id}`,
    samples: '/dashboard/samples',
    sampleDetail: (id: string) => `/dashboard/samples/${id}`,
    reports: '/dashboard/reports',
    quotations: '/dashboard/quotations',
    wallet: '/dashboard/wallet',
    referral: '/dashboard/referral',
    messages: '/dashboard/messages',
    profile: '/dashboard/profile',
    settings: '/dashboard/settings',
  },
  admin: {
    home: '/admin/dashboard',
    services: '/admin/services',
    orders: '/admin/orders',
    samples: '/admin/samples',
    reports: '/admin/reports',
    users: '/admin/users',
    labs: '/admin/labs',
    equipment: '/admin/equipment',
    finance: '/admin/finance',
    referrals: '/admin/referrals',
    cms: '/admin/cms',
    translations: '/admin/translations',
    analytics: '/admin/analytics',
    rfq: '/admin/rfq',
  },
  labPortal: {
    home: '/lab-portal/dashboard',
    orders: '/lab-portal/orders',
    samples: '/lab-portal/samples',
    reports: '/lab-portal/reports',
    equipment: '/lab-portal/equipment',
    rfq: '/lab-portal/rfq',
  },
  enterprise: {
    home: '/enterprise/workspace',
    members: '/enterprise/members',
    billing: '/enterprise/billing',
    orders: '/enterprise/orders',
    reports: '/enterprise/reports',
    approvals: '/enterprise/approvals',
  },
} as const;
